name: flutter_dialogflow
description: Flutter package for makes it easy to integrate dialogflow and support dialogflow v2
version: 0.1.2
author: Victor Alfonso Rodas OÃ±a <victordevcode@gmail.com>
homepage: https://github.com/VictorRancesCode/flutter_dialogflow

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  googleapis_auth: ^0.2.6

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter

flutter:

environment:
  sdk: '>=1.20.1 <3.0.0'
